# Generated by Django 4.0.2 on 2022-03-31 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='about_html',
            field=models.TextField(blank=True, null=True, verbose_name='About us html'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='faq_html',
            field=models.TextField(blank=True, null=True, verbose_name='Frequently Asked Questions'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='privacy_html',
            field=models.TextField(blank=True, null=True, verbose_name='About us'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='terms_html',
            field=models.TextField(blank=True, null=True, verbose_name='About us'),
        ),
    ]
