# Generated by Django 4.0.2 on 2022-06-17 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesetting_about_html_sitesetting_faq_html_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='International Whatsapp number', max_length=20, null=True),
        ),
    ]
