# Generated by Django 4.0.2 on 2022-08-09 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesetting_whatsapp_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesetting',
            name='ico_link',
        ),
    ]
