# Generated by Django 4.0.2 on 2022-03-31 01:31

from django.db import migrations
import miq.staff.models.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('core.user',),
            managers=[
                ('objects', miq.staff.models.managers.UserManager()),
            ],
        ),
    ]
