# Generated by Django 4.0.2 on 2022-09-23 19:23

from django.db import migrations, models
import django.db.models.deletion
import miq.honeypot.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='update date and time')),
                ('site_id', models.CharField(blank=True, default=1, max_length=200, null=True)),
                ('username', models.CharField(max_length=500)),
                ('password', models.CharField(max_length=500)),
                ('payload', models.JSONField(blank=True, default=miq.honeypot.models.jsondef, null=True, verbose_name='Payload')),
                ('url', models.TextField(max_length=500)),
                ('path', models.TextField(max_length=500)),
                ('referrer', models.TextField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='Ip address')),
                ('debug', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Login Attempt',
                'verbose_name_plural': 'Login Attempts',
                'ordering': ('-created', '-updated'),
            },
        ),
        migrations.CreateModel(
            name='AttemptDt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='update date and time')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='times', to='honeypot.attempt', verbose_name='Attempt')),
            ],
            options={
                'verbose_name': 'Login Attempt Datetime',
                'verbose_name_plural': 'Login Attempt Datetimes',
                'ordering': ('-created', '-updated'),
            },
        ),
    ]
