# Generated by Django 3.2.2 on 2021-05-10 17:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('miq', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='update date and time')),
                ('title', models.CharField(blank=True, help_text='Page Meta title', max_length=250, null=True)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('label', models.CharField(help_text='Page header label', max_length=100)),
                ('slug', models.SlugField(default=uuid.uuid4, max_length=200, unique=True)),
                ('is_published', models.BooleanField(default=False, help_text='Publish this page')),
                ('dt_published', models.DateTimeField(blank=True, help_text='Publication date', null=True)),
            ],
            options={
                'verbose_name': 'Page',
                'verbose_name_plural': 'Page',
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='update date and time')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, help_text='Call to action or link url', null=True)),
                ('type', models.CharField(choices=[('TXT', 'Text'), ('MD', 'Markdown'), ('IMG', 'Image'), ('JUMB', 'Jumbotron'), ('SLIDER', 'Slider'), ('EMBED', 'Embed')], default='TXT', max_length=15)),
                ('html', models.TextField(blank=True, null=True)),
                ('nodes', models.JSONField(blank=True, null=True)),
                ('position', models.PositiveIntegerField(default=1)),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
                'ordering': ('created', 'position'),
            },
        ),
        migrations.AddField(
            model_name='image',
            name='caption',
            field=models.CharField(blank=True, max_length=400),
        ),
        migrations.AlterField(
            model_name='image',
            name='position',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='SectionImageMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='update date and time')),
                ('title', models.CharField(blank=True, max_length=200, null=True)),
                ('text', models.TextField(blank=True, null=True)),
                ('url', models.URLField(blank=True, help_text='Call to action or link url', null=True)),
                ('img', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miq.image')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miq.section')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='section',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='sections', through='miq.SectionImageMeta', to='miq.Image'),
        ),
        migrations.CreateModel(
            name='PageSectionMeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='update date and time')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miq.page')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='miq.section')),
            ],
        ),
        migrations.AddField(
            model_name='page',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='pages', through='miq.PageSectionMeta', to='miq.Section'),
        ),
        migrations.AddField(
            model_name='page',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pages', to='sites.site'),
        ),
        migrations.CreateModel(
            name='Index',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='update date and time')),
                ('title', models.CharField(blank=True, help_text='Page Meta title', max_length=250, null=True)),
                ('sections', models.ManyToManyField(blank=True, to='miq.Section')),
                ('site', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='index', to='sites.site')),
            ],
            options={
                'verbose_name': 'Index page',
                'verbose_name_plural': 'Index page',
            },
        ),
        migrations.AddConstraint(
            model_name='pagesectionmeta',
            constraint=models.UniqueConstraint(fields=('page', 'section'), name='unique_page_section'),
        ),
    ]
