# Generated by Django 3.2.2 on 2021-05-10 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miq', '0002_auto_20210510_1319'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageSection',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('miq.section',),
        ),
        migrations.CreateModel(
            name='MarkdownSection',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('miq.section',),
        ),
        migrations.CreateModel(
            name='TextSection',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('miq.section',),
        ),
    ]
