# Generated by Django 3.2.2 on 2021-05-11 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miq', '0003_imagesection_markdownsection_textsection'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='index',
            options={'ordering': ('-created', '-updated'), 'verbose_name': 'Index page', 'verbose_name_plural': 'Index page'},
        ),
        migrations.AlterModelOptions(
            name='page',
            options={'ordering': ('-created', '-updated'), 'verbose_name': 'Page', 'verbose_name_plural': 'Page'},
        ),
        migrations.AlterModelOptions(
            name='pagesectionmeta',
            options={'ordering': ('-created', '-updated')},
        ),
        migrations.AddField(
            model_name='section',
            name='source',
            field=models.SlugField(blank=True, max_length=100, null=True),
        ),
    ]
