# Generated by Django 3.2.2 on 2021-05-26 11:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('miq', '0005_page_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='sites.site'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='section',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='sites.site'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sectionimagemeta',
            name='img',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meta', to='miq.image'),
        ),
    ]
