# Generated by Django 3.2.2 on 2021-05-26 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miq', '0006_auto_20210526_0741'),
    ]

    operations = [
        migrations.AddField(
            model_name='page',
            name='slug_pk',
            field=models.SlugField(editable=False, max_length=100, null=True, unique=True),
        ),
    ]
