# Generated by Django 3.2.4 on 2021-08-09 16:14

from django.db import migrations, models
import miq.models.file_mod
import miq.models.image_mod


class Migration(migrations.Migration):

    dependencies = [
        ('miq', '0004_auto_20210806_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='src',
            field=models.FileField(help_text='Select a file', max_length=500, upload_to=miq.models.file_mod.upload_to, verbose_name='File'),
        ),
        migrations.AlterField(
            model_name='image',
            name='src',
            field=models.ImageField(help_text='Select an image file', max_length=500, upload_to=miq.models.image_mod.upload_to, verbose_name='Source'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumb',
            field=models.ImageField(blank=True, help_text='Select an image file', max_length=500, null=True, upload_to=miq.models.image_mod.upload_thumb_to, verbose_name='Thumbnail'),
        ),
        migrations.AlterField(
            model_name='image',
            name='thumb_sq',
            field=models.ImageField(blank=True, help_text='Select an image file', max_length=500, null=True, upload_to=miq.models.image_mod.upload_thumb_to, verbose_name='Square Thumbnail'),
        ),
    ]
