# Generated by Django 3.2.4 on 2021-09-08 05:05

from django.db import migrations, models
import miq.models.image_mod
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('miq', '0005_auto_20210809_1214'),
    ]

    operations = [
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='update date and time')),
                ('src', models.ImageField(help_text='Select an image file', max_length=500, upload_to=miq.models.image_mod.upload_thumb_to, verbose_name='Thumbnail')),
                ('is_square', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Thumbnail',
                'verbose_name_plural': 'Thumbnails',
                'ordering': ('-updated', '-created'),
            },
            bases=(miq.models.image_mod.RendererMixin, models.Model),
        ),
        migrations.AddField(
            model_name='file',
            name='thumbnails',
            field=models.ManyToManyField(blank=True, to='miq.Thumbnail', verbose_name='Thumbnails'),
        ),
        migrations.AddField(
            model_name='image',
            name='thumbnails',
            field=models.ManyToManyField(blank=True, to='miq.Thumbnail', verbose_name='Thumbnails'),
        ),
    ]
