# Generated by Django 3.2.2 on 2021-10-19 18:56

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        ('miq', '0006_auto_20210908_0105'),
    ]

    operations = [
        migrations.CreateModel(
            name='JumbotronSection',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('miq.section',),
        ),
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='update date and time')),
                ('contact_email', models.EmailField(blank=True, help_text='Preferred contact email', max_length=400)),
                ('is_live', models.BooleanField(default=False, help_text='Turn off to prevent access to your website')),
                ('ga_tracking', models.TextField(blank=True, help_text='Google Analytics Measurement ID', null=True, verbose_name='Google Analytics Tracking ID')),
                ('fb_pixel', models.TextField(blank=True, help_text='Facebook Pixel ID', null=True, verbose_name='Facebook Pixel ID')),
                ('close_template', models.OneToOneField(blank=True, help_text='This template appears when the site is not live', null=True, on_delete=django.db.models.deletion.SET_NULL, to='miq.jumbotronsection')),
                ('site', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='sites.site')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
                'ordering': ('-created',),
            },
        ),
    ]
