# Generated by Django 3.2.2 on 2021-12-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miq', '0008_sitesetting_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='CloseTemplateSection',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('miq.section',),
        ),
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.CharField(choices=[('TXT', 'Text'), ('MD', 'Markdown'), ('IMG', 'Image'), ('JUMB', 'Jumbotron'), ('SLIDER', 'Slider'), ('EMBED', 'Embed'), ('CLOSE', 'Close Template')], default='TXT', max_length=15),
        ),
    ]
