# Generated by Django 3.2.2 on 2021-12-06 15:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miq', '0009_auto_20211203_1003'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='thumbnails',
        ),
        migrations.AddField(
            model_name='thumbnail',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='thumbnails', to='miq.image', verbose_name='Original Image'),
            preserve_default=False,
        ),
    ]
