# Generated by Django 3.2.2 on 2021-12-06 18:11

from django.db import migrations, models
import miq.models.image_mod


class Migration(migrations.Migration):

    dependencies = [
        ('miq', '0010_auto_20211206_1033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thumbnail',
            name='src',
            field=models.ImageField(blank=True, help_text='Select an image file', max_length=500, null=True, upload_to=miq.models.image_mod.upload_thumb_to, verbose_name='Thumbnail'),
        ),
    ]
