# Generated by Django 3.2.2 on 2021-12-09 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miq', '0011_alter_thumbnail_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='ct_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='ct_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='site_setting', to='miq.image', verbose_name='Close Image'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='ct_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='ct_title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
