# Generated by Django 3.2.2 on 2021-12-09 20:05

from django.db import migrations, models
import miq.models.image_mod


class Migration(migrations.Migration):

    dependencies = [
        ('miq', '0012_auto_20211209_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='src_mobile',
            field=models.ImageField(blank=True, help_text='Select an image file', max_length=500, null=True, upload_to=miq.models.image_mod.upload_to, verbose_name='Source mobile'),
        ),
    ]
