# Generated by Django 3.2.2 on 2021-12-10 13:26

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('miq', '0013_image_src_mobile'),
    ]

    operations = [
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='update date and time')),
                ('name', models.CharField(max_length=50, verbose_name='Display name')),
                ('url', models.URLField(max_length=250, verbose_name='Url')),
                ('is_external', models.BooleanField(default=False, verbose_name='Open in new tab')),
            ],
            options={
                'ordering': ('name', '-created'),
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='ct_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_setting', to='miq.image', verbose_name='Close Image'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='links',
            field=models.ManyToManyField(blank=True, to='miq.SocialLink', verbose_name='Social links'),
        ),
    ]
