# Generated by Django 3.2.2 on 2021-12-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miq', '0014_auto_20211210_0826'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CloseTemplateSection',
        ),
        migrations.RemoveField(
            model_name='sitesetting',
            name='close_template',
        ),
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.CharField(choices=[('TXT', 'Text'), ('MD', 'Markdown'), ('IMG', 'Image'), ('JUMB', 'Jumbotron'), ('SLIDER', 'Slider'), ('EMBED', 'Embed')], default='TXT', max_length=15),
        ),
    ]
