# Generated by Django 3.2.2 on 2021-12-11 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miq', '0015_auto_20211210_1054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='type',
            field=models.CharField(choices=[('TXT', 'Text'), ('MD', 'Markdown'), ('IMG', 'Image'), ('HGAL', 'Horizontal gallery'), ('VGAL', 'Vertical gallery'), ('SQGRID', 'Square grid'), ('JUMB', 'Jumbotron'), ('SLIDER', 'Slider'), ('EMBED', 'Embed')], default='TXT', max_length=15),
        ),
    ]
