# Generated by Django 3.2.2 on 2021-12-25 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miq', '0016_alter_section_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='index',
            name='sections',
            field=models.ManyToManyField(blank=True, related_name='index', to='miq.Section'),
        ),
    ]
