# Generated by Django 3.2.2 on 2022-01-02 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('miq', '0017_alter_index_sections'),
    ]

    operations = [
        migrations.AddField(
            model_name='index',
            name='cover',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='miq.image', verbose_name='Cover'),
        ),
    ]
