# Generated by Django 3.2.2 on 2022-01-03 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miq', '0018_index_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='contact_number',
            field=models.CharField(blank=True, help_text='Preferred contact number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sitesetting',
            name='contact_email',
            field=models.EmailField(blank=True, help_text='Preferred contact email', max_length=99, null=True),
        ),
    ]
