# Generated by Django 3.2.2 on 2022-01-03 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miq', '0019_auto_20220102_1920'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='whatsapp_link',
            field=models.URLField(blank=True, null=True, verbose_name='Whatsapp link'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='whatsapp_link_title',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='Whatsapp link description'),
        ),
    ]
