# Generated by Django 3.2.2 on 2022-01-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miq', '0020_auto_20220103_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='contact_number_title',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='Contact number description'),
        ),
    ]
