# Generated by Django 3.2.2 on 2022-01-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miq', '0021_sitesetting_contact_number_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesetting',
            name='contact_number_display',
            field=models.CharField(blank=True, max_length=99, null=True, verbose_name='Contact number description'),
        ),
    ]
