# Generated by Django 4.0.1 on 2022-01-15 01:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miq', '0022_sitesetting_contact_number_display'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ('position', '-updated', '-created'), 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
    ]
