# Generated by Django 4.0.2 on 2022-06-28 01:29

from django.db import migrations, models
import miq.analytics.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='update date and time')),
                ('site_id', models.CharField(max_length=500)),
                ('source_id', models.CharField(blank=True, max_length=500, null=True)),
                ('session', models.CharField(max_length=300)),
                ('session_data', models.JSONField(default=miq.analytics.models.jsondef, verbose_name='Session Data')),
                ('path', models.TextField(max_length=500)),
                ('referrer', models.TextField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='Ip address')),
                ('method', models.CharField(blank=True, max_length=50, null=True, verbose_name='Request method')),
                ('response_status', models.PositiveIntegerField(blank=True, null=True)),
                ('debug', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Hit',
                'verbose_name_plural': 'Hits',
                'ordering': ('-created', '-updated'),
            },
        ),
    ]
