# Generated by Django 4.0.2 on 2022-06-29 19:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchTerm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='update date and time')),
                ('session', models.CharField(max_length=300)),
                ('value', models.CharField(max_length=99, verbose_name='Term')),
                ('count', models.PositiveIntegerField(default=0, verbose_name='Count')),
            ],
            options={
                'verbose_name': 'Search Term',
                'verbose_name_plural': 'Search Terms',
                'ordering': ('-updated', '-created'),
            },
        ),
    ]
