# Generated by Django 4.0.2 on 2022-06-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0002_searchterm'),
    ]

    operations = [
        migrations.AddField(
            model_name='hit',
            name='url',
            field=models.TextField(default='/', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='searchterm',
            name='count',
            field=models.PositiveIntegerField(default=1, verbose_name='Count'),
        ),
    ]
