# Generated by Django 4.0.2 on 2022-07-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0005_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='Ip address'),
        ),
    ]
