# Generated by Django 4.0.2 on 2022-08-09 18:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_campaign_ip'),
    ]

    operations = [
        migrations.CreateModel(
            name='LIB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='update date and time')),
                ('name', models.SlugField(max_length=99, unique=True, verbose_name='Name')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='Is pinned')),
            ],
            options={
                'verbose_name': 'Link in bio',
                'verbose_name_plural': 'Links in bio',
                'ordering': ('-is_pinned', '-updated', '-created'),
            },
        ),
    ]
