# Generated by Django 4.0.2 on 2022-07-26 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0006_campaign_ip'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='campaign',
            options={'ordering': ('is_pinned', '-updated', '-created'), 'verbose_name': 'Campaign', 'verbose_name_plural': 'Campaigns'},
        ),
        migrations.AddField(
            model_name='campaign',
            name='is_pinned',
            field=models.BooleanField(default=False, verbose_name='Is pinned'),
        ),
    ]
