# Generated by Django 4.0.2 on 2022-08-09 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0007_lib'),
    ]

    operations = [
        migrations.AddField(
            model_name='lib',
            name='utm_content',
            field=models.TextField(blank=True, null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='lib',
            name='utm_medium',
            field=models.TextField(blank=True, help_text='social', null=True, verbose_name=''),
        ),
        migrations.AddField(
            model_name='lib',
            name='utm_source',
            field=models.TextField(blank=True, help_text='instabio', null=True, verbose_name=''),
        ),
    ]
