# Generated by Django 4.0.2 on 2022-08-17 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_lib_utm_content_lib_utm_medium_lib_utm_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lib',
            name='utm_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='lib',
            name='utm_medium',
            field=models.TextField(blank=True, help_text='social', null=True),
        ),
        migrations.AlterField(
            model_name='lib',
            name='utm_source',
            field=models.TextField(blank=True, help_text='instabio', null=True),
        ),
    ]
