# Generated by Django 4.0.2 on 2022-08-08 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0008_landing_alter_campaign_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lib',
            options={'ordering': ('-is_pinned', '-updated', '-created'), 'verbose_name': 'Link in bio', 'verbose_name_plural': 'Links in bio'},
        ),
    ]
