# Generated by Django 4.0.2 on 2022-08-18 00:59

from django.db import migrations, models
import miq.analytics.models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0009_alter_lib_utm_content_alter_lib_utm_medium_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Campaign',
        ),
        migrations.DeleteModel(
            name='SearchTerm',
        ),
        migrations.AddField(
            model_name='hit',
            name='is_bot',
            field=models.BooleanField(default=False, verbose_name='Is bot'),
        ),
        migrations.AddField(
            model_name='hit',
            name='is_parsed',
            field=models.BooleanField(default=False, verbose_name='Is bot'),
        ),
        migrations.AddField(
            model_name='hit',
            name='parsed_data',
            field=models.JSONField(default=miq.analytics.models.jsondef, verbose_name='Parsed Data'),
        ),
        migrations.AddField(
            model_name='lib',
            name='hits',
            field=models.ManyToManyField(blank=True, to='analytics.Hit', verbose_name='Hits'),
        ),
    ]
