# Generated by Django 4.0.2 on 2022-10-18 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('analytics', '0010_delete_campaign_delete_searchterm_hit_is_bot_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='update date and time')),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='Ip address')),
            ],
            options={
                'verbose_name': 'Bot',
                'verbose_name_plural': 'Bot',
                'ordering': ('-created', '-updated'),
            },
        ),
        migrations.AlterField(
            model_name='hit',
            name='is_parsed',
            field=models.BooleanField(default=False, verbose_name='Is parsed'),
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default=uuid.uuid4, editable=False, max_length=100, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='creation date and time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='update date and time')),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True, unpack_ipv4=True, verbose_name='Ip address')),
                ('is_bot', models.BooleanField(default=False, verbose_name='Is bot')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visitors', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Visitor',
                'verbose_name_plural': 'Visitors',
                'ordering': ('-updated', '-created'),
            },
        ),
        migrations.AddField(
            model_name='hit',
            name='visitor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='analytics.visitor', verbose_name='Visitor'),
        ),
    ]
